/*
 * Authorization Service
 *
 * Authorization Service manages RBAC and ABAC policies
 *
 * API version: 0.0.1
 * Contact: xi.he@hp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type AuthorizationRequest struct {
	Principal *AuthorizationRequestPrincipal `json:"principal"`
	Resource *AuthorizationRequestResource `json:"resource"`
	Request *AuthorizationRequestRequest `json:"request"`
	// Service specific context that will be used in OPA policy. Authz assigns it to  input.context. Services specific polices can refer to input.context.
	Context *interface{} `json:"context,omitempty"`
}
