/*
 * Authorization Service
 *
 * Authorization Service manages RBAC and ABAC policies
 *
 * API version: 0.0.1
 * Contact: xi.he@hp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type AuthorizationRequestPrincipal struct {
	Id string `json:"id,omitempty"`
	// Array of role ids. Array of permissions ids. It could be empty. In this case, Authz service will look up roles from DB.
	Roles []string `json:"roles,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
	// Array of permissions ids. It could be empty. In this case, Authz service will look up permissions from DB.
	Permissions []string `json:"permissions,omitempty"`
	// Type of principal. E.g. \"user\", \"client\".
	Type_ string `json:"type"`
}
