/*
 * Authorization Service
 *
 * Authorization Service manages RBAC and ABAC policies
 *
 * API version: 0.0.1
 * Contact: xi.he@hp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type AuthorizationRequestRequest struct {
	Method string `json:"method,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	// external_organization_id and organization_id just require one out of two parameter
	ExternalOrganizationId string `json:"external_organization_id,omitempty"`
	// Full path of a request.E.g. /company-service/api/v1/commpanys/1234
	Path string `json:"path,omitempty"`
}
