/*
 * Authorization Service
 *
 * Authorization Service manages RBAC and ABAC policies
 *
 * API version: 0.0.1
 * Contact: xi.he@hp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ModelError struct {
	Code int32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
